name: Manual Build
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download and Extract AMX Mod X Base
        run: |
          wget https://www.amxmodx.org/amxxdrop/1.9/amxmodx-1.9.0-git5294-base-linux.tar.gz -O base.tar.gz
          tar -xzf base.tar.gz -C . --strip-components=1
          rm base.tar.gz
  
      - name: Download and Extract Additional Modules
        run: |
          MODULES=(
            cstrike
            tfc
            dod
            ns
            ts
            esf
          )
          for MODULE in "${MODULES[@]}"; do
            wget "https://www.amxmodx.org/amxxdrop/1.9/amxmodx-1.9.0-git5294-${MODULE}-linux.tar.gz" -O "${MODULE}.tar.gz"
            tar -xzf "${MODULE}.tar.gz" -C . --strip-components=1
            rm "${MODULE}.tar.gz"
          done

      - name: Clean existing .sma files (we dont need them)
        run: |
          rm amxmodx/scripting/*.sma
          
      - name: Copy files to Scripting Directory
        run: |
          cp -R scripting/* amxmodx/scripting/
  
      - name: Verify Setup
        run: |
          echo "Contents of amxmodx directory:"
          tree amxmodx/scripting

      - name: Compile Repository Plugins
        run: |
          cd amxmodx/scripting
          ./compile.sh

      - name: Verify compiled conents
        run: |
          echo "Contents of compiled directory:"
          tree amxmodx/scripting/compiled

      - name: Compile Repository Plugins
        run: |
          mkdir plugins
          cp amxmodx/scripting/compiled/*.amxx plugins
          rm -rf amxmodx

      - name: Upload Compiled Scripts as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.repository.name}}-compiled
          path: .
